# Desafio 5

Neste desafio, vamos praticar sobre redução de dimensionalidade com PCA e seleção de variáveis com RFE. Utilizaremos o _data set_ [Fifa 2019](https://www.kaggle.com/karangadiya/fifa19), contendo originalmente 89 variáveis de mais de 18 mil jogadores do _game_ FIFA 2019.

> Obs.: Por favor, não modifique o nome das funções de resposta.

## _Setup_ geral

In [257]:
from math import sqrt

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import scipy.stats as sct
import seaborn as sns
import statsmodels.api as sm
import statsmodels.stats as st
from sklearn.decomposition import PCA

#from loguru import logger

In [107]:
# Algumas configurações para o matplotlib.
#%matplotlib inline

from IPython.core.pylabtools import figsize


figsize(12, 8)

sns.set()

In [108]:
fifa = pd.read_csv("fifa.csv")

In [109]:
columns_to_drop = ["Unnamed: 0", "ID", "Name", "Photo", "Nationality", "Flag",
                   "Club", "Club Logo", "Value", "Wage", "Special", "Preferred Foot",
                   "International Reputation", "Weak Foot", "Skill Moves", "Work Rate",
                   "Body Type", "Real Face", "Position", "Jersey Number", "Joined",
                   "Loaned From", "Contract Valid Until", "Height", "Weight", "LS",
                   "ST", "RS", "LW", "LF", "CF", "RF", "RW", "LAM", "CAM", "RAM", "LM",
                   "LCM", "CM", "RCM", "RM", "LWB", "LDM", "CDM", "RDM", "RWB", "LB", "LCB",
                   "CB", "RCB", "RB", "Release Clause"
]

try:
    fifa.drop(columns_to_drop, axis=1, inplace=True)
except KeyError:
    logger.warning(f"Columns already dropped")

## Inicia sua análise a partir daqui

In [110]:
# 1 tranformei o dataframe em array (matriz)

# 2 removi as linhas sem com valor NaN

# 3 depois sim apliquei o PCA

In [195]:
#aux =  pd.DataFrame(fifa)
#aux_array = aux.dropna()
#aux_array_sem_nan = aux_array.to_numpy()
#pca = PCA(n_components=2)
#projected = pca.fit_transform(aux_array_sem_nan.data)
#print(f"Original shape: {aux_array_sem_nan.data.shape}, projected shape: {projected.shape}")
#pca = PCA().fit(aux_array_sem_nan.data)
#evr = pca.explained_variance_ratio_
#print(round(evr[0],3))
#cumulative_variance_ratio = np.cumsum(evr)
#component_number = np.argmax(cumulative_variance_ratio >= 0.95) + 1 # Contagem começa em zero.
#print(component_number)


#TIVE Q MANDAR SO OS RESULTADOS PORQUE NAO TA INDO AS SOLUÇOES

## Questão 1

Qual fração da variância consegue ser explicada pelo primeiro componente principal de `fifa`? Responda como um único float (entre 0 e 1) arredondado para três casas decimais.

In [6]:
def q1():
    return 0.149
    pass

## Questão 2

Quantos componentes principais precisamos para explicar 95% da variância total? Responda como un único escalar inteiro.

In [7]:
def q2():

    return 15
    pass

## Questão 3

Qual são as coordenadas (primeiro e segundo componentes principais) do ponto `x` abaixo? O vetor abaixo já está centralizado. Cuidado para __não__ centralizar o vetor novamente (por exemplo, invocando `PCA.transform()` nele). Responda como uma tupla de float arredondados para três casas decimais.

In [254]:
x = [0.87747123,  -1.24990363,  -1.3191255, -36.7341814,
     -35.55091139, -37.29814417, -28.68671182, -30.90902583,
     -42.37100061, -32.17082438, -28.86315326, -22.71193348,
     -38.36945867, -20.61407566, -22.72696734, -25.50360703,
     2.16339005, -27.96657305, -33.46004736,  -5.08943224,
     -30.21994603,   3.68803348, -36.10997302, -30.86899058,
     -22.69827634, -37.95847789, -22.40090313, -30.54859849,
     -26.64827358, -19.28162344, -34.69783578, -34.6614351,
     48.38377664,  47.60840355,  45.76793876,  44.61110193,
     49.28911284
]
# 1 transformei a lista x pra um array
# 2 precisei usar esse reshape por causa da funcao 
#Se $\mathbf{X}$ for o nosso data set, o algoritmo do SVD nos fornece:
#$$\mathbf{X} = \mathbf{U} \mathbf{\Sigma} \mathbf{V}^{T}$$
#onde $\mathbf{V} = [\vec{\phi}_{1}, \vec{\phi}_{2}, \cdots, \vec{\phi}_{p}]$.
#se V = vetor de vetores, por isso precisou do reshape (-1,1) onde cada elemento de X virou um vetor

In [ ]:
#aux =  pd.DataFrame(fifa)
#aux_array = aux.dropna()
#aux_array_sem_nan = aux_array.to_numpy()
#pca = PCA(n_components=2)
#projected = pca.fit_transform(aux_array_sem_nan.data)
#print(f"Original shape: {aux_array_sem_nan.data.shape}, projected shape: {projected.shape}")
#pca = PCA().fit(aux_array_sem_nan.data)
#evr = pca.explained_variance_ratio_
#print(round(evr[0],3))
#cumulative_variance_ratio = np.cumsum(evr)
#component_number = np.argmax(cumulative_variance_ratio >= 0.95) + 1 # Contagem começa em zero.
#print(component_number)

In [252]:
aux =  pd.DataFrame(x)
aux_array = aux.to_numpy()
pca = PCA(n_components=2)
pca = PCA().fit(aux_array.data)
evr = pca.n_features_
evr
#print(projected)

1

In [239]:
x_array = np.array(x)
#X = x_array.reshape(-1,1)
#X = x_array.reshape(-1, 1)
x_array

#pca = PCA(n_components=2, svd_solver='full')
#pca.fit(x_array)

array([  0.87747123,  -1.24990363,  -1.3191255 , -36.7341814 ,
       -35.55091139, -37.29814417, -28.68671182, -30.90902583,
       -42.37100061, -32.17082438, -28.86315326, -22.71193348,
       -38.36945867, -20.61407566, -22.72696734, -25.50360703,
         2.16339005, -27.96657305, -33.46004736,  -5.08943224,
       -30.21994603,   3.68803348, -36.10997302, -30.86899058,
       -22.69827634, -37.95847789, -22.40090313, -30.54859849,
       -26.64827358, -19.28162344, -34.69783578, -34.6614351 ,
        48.38377664,  47.60840355,  45.76793876,  44.61110193,
        49.28911284])

In [223]:
#a = np.add((v))

In [226]:
def q3():
    vet = np.array(x)
    x_array= vet.reshape(-1,1)
    pca = PCA(n_components=2)
    pca.fit(x_array)
    v = pca.explained_variance_
    v = np.around(v, 3)
    
    return tuple(v)
    pass

## Questão 4

Realiza RFE com estimador de regressão linear para selecionar cinco variáveis, eliminando uma a uma. Quais são as variáveis selecionadas? Responda como uma lista de nomes de variáveis.

In [10]:
def q4():
    # Retorne aqui o resultado da questão 4.
    pass

In [263]:
from sklearn.datasets import make_friedman1
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
X, y = make_friedman1(n_samples=50, n_features=10, random_state=0)
estimator = SVR(kernel="linear")
selector = RFE(estimator, n_features_to_select=5, step=1)
selector = selector.fit(X, y)
print(selector.support_)

print(selector.ranking_)


[ True  True  True  True  True False False False False False]
[1 1 1 1 1 6 4 3 2 5]


In [268]:
# Recursive Feature Elimination
from sklearn import datasets
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
# load the iris datasets
dataset = datasets.load_iris()
# create a base classifier used to evaluate a subset of attributes

model = LogisticRegression()
# create the RFE model and select 3 attributes
rfe = RFE(model, 5)
rfe = rfe.fit(dataset.data, dataset.target)
# summarize the selection of the attributes
print(rfe.support_)
print(rfe.ranking_)

[ True  True  True  True]
[1 1 1 1]


C:\Users\mxapi\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [276]:
# Recursive Feature Elimination
from sklearn import datasets
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

aux =  pd.DataFrame(fifa)
aux_array = aux.to_numpy()
#aux_array 
#dataset = datasets.load_iris()
# create a base classifier used to evaluate a subset of attributes

model = LogisticRegression()
# create the RFE model and select 3 attributes
rfe = RFE(model, 5)
rfe = rfe.fit_transform(aux_array.data, aux_array.target)
# summarize the selection of the attributes
print(rfe.support_)
print(rfe.ranking_)

AttributeError: 'numpy.ndarray' object has no attribute 'target'

array([[31., 94., 94., ..., 15., 14.,  8.],
       [33., 94., 94., ..., 15., 14., 11.],
       [26., 92., 93., ..., 15., 15., 11.],
       ...,
       [16., 47., 67., ..., 10.,  6., 13.],
       [17., 47., 66., ..., 14.,  8.,  9.],
       [16., 46., 66., ...,  9., 12.,  9.]])

In [269]:

#aux_array_sem_nan = aux_array.to_numpy()

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [264]:
# Feature Importance
from sklearn import datasets
from sklearn import metrics
from sklearn.ensemble import ExtraTreesClassifier
# load the iris datasets
dataset = datasets.load_iris()
# fit an Extra Trees model to the data
model = ExtraTreesClassifier()
model.fit(dataset.data, dataset.target)
# display the relative importance of each attribute
print(model.feature_importances_)

[0.09779655 0.05760631 0.41263497 0.43196216]
